### ISSUE TITLE
Folder button on instance doesn't open folder

### ISSUE THREAD

**Issue by Aces-and-Jacks** [PrismLauncher/PrismLauncher#3635]
### Operating System

macOS

### Version of Prism Launcher

Prism Launcher 9.4 

### Version of Qt

Qt 6.7.3 

### Description of bug

I updated a modpack from modrinth called cobblemon from a version that's no longer on modrinth to a current version that is on modrinth. And I can open up the instance on prism launcher but I can't open the folder. 

### Steps to reproduce

Have an old instance which it's version isn't on Modrinth (Cobblemon 1.4) 

Update to existing version (Cobblemon 1.6.1) 

Folder doesn't work 

### Suspected cause

Updated from a version that's no longer there. But no clue why it won't work. Maybe didn't link correctly. 

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Aces-and-Jacks** [comment]
I know I could've just deleted and redownloaded but that would pose an issue if I had more progress and installed specific mods and had specific folders

**Comment by Aces-and-Jacks** [comment]
I think this is the prism log https://mclo.gs/sXgE5Gt

**Comment by kthchew** [comment]
```
0.860 D | Loaded instance  "Cobblemon [Fabric] 1.4.1"  from  "/Volumes/T7_MCPL_JW/PrismLauncher/instances/Cobblemon [Fabric]"
```
Is this the instance that was giving you problems? It seems possible that the `[` and `]` characters in the directory name are causing issues, and I can reproduce this issue by creating a test instance with those characters. If you remove those special characters from the folder name using Finder (for example, rename the folder from `Cobblemon [Fabric]` to something like `Cobblemon Fabric`), do you still see the same problem?

**Comment by Aces-and-Jacks** [comment]
That may have been it. Thank you for taking a look. I appreciate that. 

Unfortunately I've already deleted the instance. I was hoping a maintainer would see this and potentially make a fix for this in case it happens in the future. 

I guess I'll leave this open and if no one responds in a month I'll close.

**Comment by kthchew** [comment]
Looking at the code I'm not seeing anything wrong on Prism Launcher's side. In fact if [the code](https://github.com/PrismLauncher/PrismLauncher/blob/d88d32b917e99cd26dc9a40ab24bec06337f90ca/launcher/DesktopServices.cpp#L66) is changed to convert the QUrl to something like a CFURL and then use the native macOS API for opening URLs it opens just fine. It seems to break after going into Qt's QDesktopServices code.

My conclusion is that this is probably a Qt bug that is already fixed. When I try on the version of Prism Launcher from the official site (Qt 6.7.3) it breaks. When I try on a locally built Prism Launcher (Qt 6.9.0) I can't reproduce this bug. I'm guessing that it will eventually be fixed by a Prism Launcher update that adopts a newer Qt version.

Current development version (on Qt 6.8.1) is still affected though.

**Comment by Aces-and-Jacks** [comment]
Ah alright. So when qt is updated the problem will fix itself. If that's the case I'll close this then. Also since I don't plan to actively moniter this issue. Thank you again for your help

**Comment by EdusgprNetwork** [comment]
Hi, I'm on Qt 6.8.3, and this issue still happens to me 

I'm on my steamdeck/steamOS and I tried reinstalling prism from scratch a few times and the issue persists. What happens is: 
-I make a new instance, any version or modpack
-I try using any of the buttons to open folders, and they dont work
Open Instance folder, config, mods, and even in game buttons like the Open ResourcePack folder button, none work

I even tried manually changing the folder into a different directory (I made a folder in /home/deck/Applications/PrismLauncher/instances) and that had no effect.

I just need to know if there's any fixes, or planned fixes for this, or if it's unsolvable due to something to do with steamOS 

Steps I took:
-install Prism Launcher
(optional) - Change Instances folder in the settings to a different folder (didn't work)
-Create new instance (any version or pack)
-Try using any button related to opening a folder
-Try running instance and using the Open ResourcePack folder (Or any other open folder button)
-doesn't work

**Comment by Aces-and-Jacks** [comment]
Your issue seems a little different than mine. For me it had only happened when updating an old instance. But for the most part my instances still work fine. And it was on MacOS

But then again I don't really know code, so I couldn't really figure out whats wrong. You may want to make a new issue, but you can link to this one if you want. You may also want to ask in the discord

**Comment by Kan5661** [comment]
Having the same issue on my cobblemon official mod pack. Tried changing the pack name and it doesnt work. Can open folder of all my other instances though.

**Comment by Kan5661** [comment]
Found out that renaming the instance doesnt actually change the folder's name in PrismLauncher/instances. You gotta go to finder and change the folder name which fixes this issue. So i guess the problem was with the parenthesis
