### ISSUE TITLE
my prism launcher wont launch (im not using a vpn)

### ISSUE THREAD

**Issue by tyyme2000** [PrismLauncher/PrismLauncher#4267]
### Operating System

Windows

### Version of Prism Launcher

9.4

### Version of Qt

idk

### Description of bug

so its stuck at some random thing prism does before launching and it never complets it

<img width="653" height="258" alt="Image" src="https://github.com/user-attachments/assets/d3b61c3a-9550-4b21-ba1b-5366a149f8a2" />

### Steps to reproduce

open the launcher select a version click play 

### Suspected cause

i dont know actually

### This issue is unique

- [x] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by GillisC** [comment]
Im having the same issue.

**Comment by marighost** [comment]
Both myself (CachyOS using official binary) and my partner (Mint 22 Flatpak) are having this exact same issue.

**Comment by Buzzyboyish** [comment]
Same issue here.

**Comment by KoenEU** [comment]
Same.
Seems to be a problem with [mojangs services](https://downdetector.com/status/minecraft/) right now, not prism launcher.
Many reports on the [minecraft reddit](https://www.reddit.com/r/Minecraft/new/) of people without prism launcher having similar issues.

**Comment by LunarChimeraa** [comment]
Me and two of my friends are also dealing with this since last night :( rip

**Comment by tyyme2000** [comment]
ahh ok guys il wait

**Comment by Hydra-a-a** [comment]
Mojang Services are down, same with AWS and Microsoft Azure, let's just wait.

https://downdetector.com/status/minecraft/

**Comment by Hydra-a-a** [comment]
If you guys play singleplayer, just right click launch on the instance you want to play, and select offline mode. That should fix it.

For multiplayer, wait for the servers to go back up is all we can do.

**Comment by electricsteve** [comment]
<img width="1261" height="173" alt="Image" src="https://github.com/user-attachments/assets/d2543a12-72ee-4e43-a3a2-ebf35437ba54" />
The creators know. Offline mode also doesn't work because it tries to verify the hashes of the minecraft and it can't because the servers it gets the hashes from are offline. If you really want to play rip out your internet cable/wifi.

**Comment by tyyme2000** [comment]
and now i need to use the old pirated TL bruh

**Comment by docjyJ** [comment]
By launching offline mode, it is not possible to connect to the server.
And with an offline mod account Prism try to connect to Mojang server so I can't play on my server...

**Comment by tyyme2000** [comment]
still not fixed 

<img width="1070" height="822" alt="Image" src="https://github.com/user-attachments/assets/3740a187-957c-41b2-8d51-da6e5f618a69" />

**Comment by electricsteve** [comment]
> still not fixed
> <img alt="Image" width="1070" height="822" src="https://private-user-images.githubusercontent.com/240962974/507272244-3740a187-957c-41b2-8d51-da6e5f618a69.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE3NjkwNDcsIm5iZiI6MTc2MTc2ODc0NywicGF0aCI6Ii8yNDA5NjI5NzQvNTA3MjcyMjQ0LTM3NDBhMTg3LTk1N2MtNDFiMi04ZDUxLWRhNmU1ZjYxOGE2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAyOVQyMDEyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmRkYzcyNGQ1ZTBiMWM5NTQ5N2U2Mzc5NTVlMjI4ZThjZTlkODUwMTVjYWEzMjNkYTUzNTk2NmE3MzIzYjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wkewwirUEZZW2jvTEEMbRSQsSk2tbNnEKT5kZsON2pQ">

It's not a prism launcher issue, no one can play minecraft right now

**Comment by Trial97** [comment]
Was caused by outrage of Microsoft servers

**Comment by egornewacc610-cell37821** [comment]
How to fix that? @Trial97 do you find an answer on this question?

**Comment by electricsteve** [comment]
> How to fix that? [@Trial97](https://github.com/Trial97) do you find an answer on this question?

At the time this issue was created the mojang servers were down. If you are still having problems make a new issue.
