### ISSUE TITLE
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id

### ISSUE THREAD

**Issue by n8marti** [PrismLauncher/PrismLauncher#686]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 6.1 (installed using pi-apps)

### Version of Qt

Qt 5.15.2

### Description of bug

PrismLauncher fails to connect to any websites that use SSL. The first instance is:
```
0.481 D Downloading  "https://i18n.prismlauncher.org/index_v2.json"
0.486 W QSslSocket: cannot resolve EVP_PKEY_base_id
0.486 W QSslSocket: cannot resolve SSL_get_peer_certificate
```
Then later:
```
0.497 D Downloading  "https://prismlauncher.org/feed/feed.xml"
1.334 W QSslSocket: cannot call unresolved function SSL_get_peer_certificate
1.343 C Download "https://i18n.prismlauncher.org/index_v2.json" SSL Error # 1  :  "The peer did not present any certificate"
```

### Steps to reproduce

Start PrismLauncher in terminal: ```$ prismlauncher```; observe terminal output

### Suspected cause

Probably mismatched libssl package?

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Scrumplex** [comment]
CC @theofficialgman

**Comment by theofficialgman** [comment]
what distro?

```
~/pi-apps/api get_device_info
```

**Comment by n8marti** [comment]
```
OS: Armbian 22.08.1 Jammy
OS architecture: 64-bit
Last updated Pi-Apps on: 12/28/2022
Latest Pi-Apps version: 12/28/2022
Kernel: aarch64 5.15.63-rockchip64
Device model: Pine64 Pinebook Pro
Cpu name: Cortex-A53
Cortex-A72
Ram size: 3.86 GB
Language: en_US.UTF-8
```

**Comment by theofficialgman** [comment]
ah ok, jammy uses libssl3
our supported distros (buster, bionic, bullseye) use libssl1.1.1

I can update the package to include bionic's libssl1.1.1 binary which receives security updates and should be compatible with the package

**Comment by DioEgizio** [comment]
> ah ok, jammy uses libssl3 our supported distros (buster, bionic, bullseye) use libssl1.1.1
> 
> I can update the package to include bionic's libssl1.1.1 binary which receives security updates and should be compatible with the package

Yeah you need to do it, we do it on our appimages because it just doesn't work on systems with openssl 3 if we don't

**Comment by theofficialgman** [comment]
completed @n8marti update prism from pi-apps and this should be fixed

**Comment by n8marti** [comment]
beautiful: problem solved!

**Comment by davidgarland** [comment]
If I'm using a source-built version of prism on a distro whose main OpenSSL version is 3 but I have 1.1.1 built, how do I get it working? By that I mean `/usr/lib` looks like:
```
libcrypto.a
libcrypto.so -> libcrypto.so.3
libcrypto.so.1.1
libcrypto.so.3
...
libssl.a
libssl.so -> libssl.so.3
libssl.so.1.1
libssl.so.3
libssl3.so
```
anything I can do to make prism detect that `libssl.so.1.1`/`libcrypto.so.1.1`?

**Comment by DioEgizio** [comment]
what? Explain better please, if you have a Qt version linked with openssl 3 it should just work

**Comment by davidgarland** [comment]
I have Qt built from source on a system which has openssl3... no idea what is going wrong, exactly. The error log I get is identical (enough) to that of the OP, though:

```
     0.000 D | <> Log initialized.
     0.000 D | <> No migration needed from "PolyMC"
     0.000 D | <> No migration needed from "MultiMC"
     0.000 D | "Prism Launcher" , (c) 2013-2021  "Prism Launcher Contributors\n© 2021-2022 PolyMC Contributors \n© 2012-2021 MultiMC Contributors"
     0.000 D | Version                    :  "7.0-master"
     0.000 D | Git commit                 :  "d5d4f872363c59efa503996208c37ee98ef4ec7e"
     0.000 D | Git refspec                :  "refs/heads/master"
     0.000 D | Work dir before adjustment :  "/home/david"
     0.000 D | Work dir after adjustment  :  "/home/david/.local/share/PrismLauncher"
     0.000 D | Adjusted by                :  "Persistent data path"
     0.000 D | Binary path                :  "/usr/bin"
     0.000 D | Application root path      :  "/usr"
     0.000 D | <> Paths set.
     0.000 D | Copied settings from "polymc.cfg" to "prismlauncher.cfg"
     0.001 D | Detected default console font: "Fantasque Sans Mono" , substitutions: ""
     0.008 D | <> Settings loaded.
     0.009 D | Detecting proxy settings...
     0.009 D | Using no proxy is an option!
     0.009 D | <> Network done.
     0.009 C | Exception: "Unable to open /home/david/.local/share/PrismLauncher/translations/index_v2.json for reading: No such file or directory"
     0.009 C | Translations Download Failed: index file not readable
     0.009 D | Your language is "en_US"
     0.009 D | <> Translations loaded.
     0.009 D | Started watching  "/home/david/.local/share/PrismLauncher/icons"
     0.009 D | Sorting icon list...
     0.009 D | <> Instance icons intialized.
     0.009 D | [Theme] <> Icon themes initialized.
     0.009 D | [Theme] <> Initializing Widget Themes
     0.009 D | [Theme] Determining System Theme...
     0.009 D | [Theme] System theme seems to be: "fusion"
     0.009 D | [Theme] Considering theme from theme factory: "windows"
     0.009 D | [Theme] Considering theme from theme factory: "fusion"
     0.009 D | [Theme] System theme has been determined to be: "Fusion"
     0.009 D | [Theme] Loading Built-in Theme: "system"
     0.009 D | [Theme] Loading Built-in Theme: "dark"
     0.009 D | [Theme] Loading Built-in Theme: "bright"
     0.009 D | [Theme] Theme Folder Path:  "/home/david/.local/share/PrismLauncher/themes"
     0.009 D | [Theme] Loading JSON Theme from: "/home/david/.local/share/PrismLauncher/themes/custom/theme.json"
     0.009 D | [Theme] <> Widget themes initialized.
     0.009 D | Instance path              :  "instances"
     0.009 D | Loading Instances...
     0.009 D | Discovering instances in "/home/david/.local/share/PrismLauncher/instances"
     0.009 D | <> Instances loaded.
     0.009 D | Loading accounts...
     0.009 C | "Failed to read the account list file (accounts.json)."
     0.009 D | <> Accounts loaded.
     0.009 D | <> Cache initialized.
     0.009 D | Downloading Translations Index...
     0.009 D | Task "NetJob(Translations Index)" starting for the first time
     0.010 D | [Theme] <> Icon theme set.
     0.010 D | [Theme] applying theme "System"
     0.010 D | [Theme] <> Application theme set.
     0.018 D | Reloading news.
     0.018 D | Task "NetJob(News RSS Feed)" starting for the first time
     0.039 D | <> Main window shown.
     0.039 D | Task "Net::Download(0x560c24a29f10)" starting for the first time
     0.039 D | Downloading  "https://prismlauncher.org/feed/feed.xml"
     0.039 W | [qt.network.ssl]: QSslSocket: cannot resolve EVP_PKEY_base_id
     0.039 W | [qt.network.ssl]: QSslSocket: cannot resolve SSL_get_peer_certificate
     0.060 D | Task "Net::Download(0x560c249b6870)" starting for the first time
     0.060 D | Downloading  "https://i18n.prismlauncher.org/index_v2.json"
     0.316 W | [qt.network.ssl]: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
     0.317 C | Download "https://i18n.prismlauncher.org/index_v2.json" SSL Error # 1  :  "The peer did not present any certificate"
     0.317 C | Certificate in question:
 ""
     0.317 C | Failed  "https://i18n.prismlauncher.org/index_v2.json"  with reason  QNetworkReply::SslHandshakeFailedError
     0.317 D | Download failed in previous step: "https://i18n.prismlauncher.org/index_v2.json"
     0.317 D | Task "Net::Download(0x560c249b6870)" restarting for after failing at first
     0.317 D | Downloading  "https://i18n.prismlauncher.org/index_v2.json"
     0.351 W | [qt.network.ssl]: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
     0.351 C | Download "https://i18n.prismlauncher.org/index_v2.json" SSL Error # 1  :  "The peer did not present any certificate"
     0.351 C | Certificate in question:
 ""
     0.351 C | Failed  "https://i18n.prismlauncher.org/index_v2.json"  with reason  QNetworkReply::SslHandshakeFailedError
     0.351 D | Download failed in previous step: "https://i18n.prismlauncher.org/index_v2.json"
     0.351 D | Task "Net::Download(0x560c249b6870)" restarting for after failing at first
     0.351 D | Downloading  "https://i18n.prismlauncher.org/index_v2.json"
     0.384 W | [qt.network.ssl]: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
     0.384 C | Download "https://i18n.prismlauncher.org/index_v2.json" SSL Error # 1  :  "The peer did not present any certificate"
     0.384 C | Certificate in question:
 ""
     0.384 C | Failed  "https://i18n.prismlauncher.org/index_v2.json"  with reason  QNetworkReply::SslHandshakeFailedError
     0.384 D | Download failed in previous step: "https://i18n.prismlauncher.org/index_v2.json"
     0.384 D | Task "NetJob(Translations Index)" succeeded
     0.384 D | Got translations index!
     0.452 W | [qt.network.ssl]: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
     0.452 C | Download "https://prismlauncher.org/feed/feed.xml" SSL Error # 1  :  "The peer did not present any certificate"
     0.452 C | Certificate in question:
 ""
     0.452 C | Failed  "https://prismlauncher.org/feed/feed.xml"  with reason  QNetworkReply::SslHandshakeFailedError
     0.452 D | Download failed in previous step: "https://prismlauncher.org/feed/feed.xml"
     0.453 D | Task "Net::Download(0x560c24a29f10)" restarting for after failing at first
     0.453 D | Downloading  "https://prismlauncher.org/feed/feed.xml"
     0.557 W | [qt.network.ssl]: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
     0.557 C | Download "https://prismlauncher.org/feed/feed.xml" SSL Error # 1  :  "The peer did not present any certificate"
     0.557 C | Certificate in question:
 ""
     0.557 C | Failed  "https://prismlauncher.org/feed/feed.xml"  with reason  QNetworkReply::SslHandshakeFailedError
     0.557 D | Download failed in previous step: "https://prismlauncher.org/feed/feed.xml"
     0.557 D | Task "Net::Download(0x560c24a29f10)" restarting for after failing at first
     0.557 D | Downloading  "https://prismlauncher.org/feed/feed.xml"
     0.662 W | [qt.network.ssl]: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
     0.663 C | Download "https://prismlauncher.org/feed/feed.xml" SSL Error # 1  :  "The peer did not present any certificate"
     0.663 C | Certificate in question:
 ""
     0.663 C | Failed  "https://prismlauncher.org/feed/feed.xml"  with reason  QNetworkReply::SslHandshakeFailedError
     0.663 D | Download failed in previous step: "https://prismlauncher.org/feed/feed.xml"
     0.663 D | Task "NetJob(News RSS Feed)" succeeded
     0.663 D | Finished loading RSS feed.
     0.663 D | Failed to load news: "Error parsing RSS feed XML. unexpected end of file at 1:1."
     5.532 D | Task "MSAInteractive(0x560c256b1580)" starting for the first time
     5.532 D | AuthFlow: "Logging in with Microsoft account."
     5.532 D | DeviceFlow::link
     5.532 D | DeviceFlow::setLinked: false
     5.710 W | [qt.network.ssl]: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
     5.710 D | DeviceFlow::onDeviceAuthReplyFinished
    16.583 D | Paged dialog close requested
    16.583 D | Sorting icon list...
    16.583 D | Detecting proxy settings...
    16.583 D | Using no proxy is an option!
    16.583 D | Paged dialog close approved
    16.583 D | Paged dialog geometry saved
    16.599 D | Discovering instances in "/home/david/.local/share/PrismLauncher/instances"
```

Rebuilding OpenSSL, every Qt package I have, then prism launcher (in that order) doesn't seem to fix the issue. The issue results in me trying to log in with a microsoft account and getting a hanging window saying "Working..." waiting for the request to send.

**Comment by davidgarland** [comment]
After rebuilding qt5 with the `-openssl-linked` option it works. I kinda just assumed it should be able to load it dynamically at runtime by finding it, since I've seen people say that's how it typically works.. my bad. Thank you for the assistance ^^
